matrix:
  include:
    - os: osx
      language: objective-c # this is a lie
      xcode_project: CommandLine.xcodeproj
      xcode_scheme: CommandLine
      script: xcodebuild -scheme CommandLine test
      osx_image: xcode10.2
    - os: linux
      dist: xenial
      sudo: false
      services: docker
      before_install:
        - docker pull swift:latest
      script:
        - docker run -v "$(pwd):/src" swift:latest /src/script/test
